# fly.toml app configuration file
app = 'pathforge-prototype'
primary_region = 'ord'

[build]

[deploy]
  release_command = "./setup_database.sh"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "20s"
    interval = "15s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
